//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Financa
    {
        public int IdFinanca { get; set; }
        public int IdCategoria { get; set; }
        public int IdTipoFinanca { get; set; }
        public string Descricao { get; set; }
        public double Valor { get; set; }
        public bool Fechada { get; set; }
        public bool Paga { get; set; }
        public byte[] Comprovante { get; set; }
        public System.DateTime Data { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual TipoFinanca TipoFinanca { get; set; }
    }
}
