//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FP.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoFinanca
    {
        public TipoFinanca()
        {
            this.Financas = new HashSet<Financa>();
        }
    
        public int IdTipoFinanca { get; set; }
        public string Descricao { get; set; }
    
        public virtual ICollection<Financa> Financas { get; set; }
    }
}
